[tools]
usage = "latest"
node = { version = "lts", postinstall = "npx corepack enable && echo \"corepack enabled!\"" }
dotnet = "9"
awscli = "latest"
deno = "2"
claude = "2"
bat = "latest"
difftastic = "latest"
elixir = "1.18"
eza = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
go = "1"
hyperfine = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
shellcheck = "latest"
uv = "latest"
opencode = "latest"
jj = "latest"
"cargo:tree-sitter-cli" = "latest"

[settings]
# This must be enabled to make the hooks work appropriately
experimental = true
lockfile = true
