# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
promptToReturnFromSubprocess: false
os:
  editPreset: "nvim"
git:
  paging:
    externalDiffCommand: difft --display inline --context 3 --color always
  autoForwardBranches: "none"
